[package]
name = "snowbridge-testutils"
version = "0.1.0"
authors = [ "Snowfork <contact@snowfork.com>" ]
edition = "2021"

[dependencies]
ethereum-types = { version = "0.14.1", default-features = false }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
serde = { version = "1.0.160", features = [ "derive" ] }
serde_json = "1.0.96"
