[package]
name = "snowbridge-beacon-primitives"
version = "0.0.1"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.160", optional = true, features = ["derive"] }
hex = { version = "0.4", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = [
    "derive",
] }
rlp = { version = "0.5", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }

ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", default-features = false, rev = "d18af912abacbf84219be37ab3b42a9abcf10d2a" }
ssz-rs-derive = { git = "https://github.com/ralexstokes/ssz-rs", default-features = false, rev = "d18af912abacbf84219be37ab3b42a9abcf10d2a" }
byte-slice-cast = { version = "1.2.1", default-features = false }

snowbridge-ethereum = { path = "../../primitives/ethereum", default-features = false }
static_assertions = { version = "1.1.0" }
# milagro_bls = { path = "../../../../milagro_bls", default-features = false }
milagro_bls = { git = "https://github.com/snowfork/milagro_bls", default-features = false, rev="a6d66e4eb89015e352fb1c9f7b661ecdbb5b2176"}

[dev-dependencies]
hex-literal = { version = "0.4.1" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-io/std",
    "rlp/std",
    "snowbridge-ethereum/std",
    "ssz-rs/std",
    "byte-slice-cast/std",
    "milagro_bls/std",
]
