[package]
name = "snowbridge-outbound-queue-merkle-proof"
description = "Snowbridge Outbound Queue Merkle Prover"
version = "0.1.1"
edition = "2021"
authors = [ "Snowfork <contact@snowfork.com>" ]
repository = "https://github.com/Snowfork/snowbridge"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec = { version = "3.1.5", package = "parity-scale-codec", default-features = false, features = [ "derive" ] }

sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }

[dev-dependencies]
hex-literal = { version = "0.3.4" }
env_logger = "0.9"
hex = "0.4"
array-bytes = "4.1"

[features]
default = [ "std" ]
std = [
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
]
