[package]
name = "snowbridge-xcm-support"
description = "Snowbridge XCM Support Pallet"
version = "0.1.1"
edition = "2021"
authors = [ "Snowfork <contact@snowfork.com>" ]
repository = "https://github.com/Snowfork/snowbridge"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec = { version = "3.1.5", package = "parity-scale-codec", features = [ "derive" ], default-features = false }
scale-info = { version = "2.3.1", default-features = false, features = [ "derive" ] }

frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "master" }
frame-system = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
pallet-xcm = { git = "https://github.com/paritytech/polkadot.git", branch = "master", default-features = false }

xcm = { git = "https://github.com/paritytech/polkadot.git", branch = "master", default-features = false }
xcm-executor = { git = "https://github.com/paritytech/polkadot.git", branch = "master", default-features = false }
xcm-builder = { git = "https://github.com/paritytech/polkadot.git", branch = "master", default-features = false }

snowbridge-xcm-support-primitives = { path = "../../primitives/xcm-support", default-features = false }

[dev-dependencies]
serde = { version = "1.0.137" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
	"pallet-xcm/std",
	"xcm/std",
	"xcm-executor/std",
	"xcm-builder/std",
	"snowbridge-xcm-support-primitives/std"
]
