[package]
name = "snowbridge-ethereum"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.130", optional = true }
serde-big-array = { version = "0.3.2", optional = true, features = ["const-generics"] }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
ethbloom = { version = "0.11.0", default-features = false }
ethereum-types = { version = "0.12.0", default-features = false, features = ["codec", "rlp", "serialize"] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
hex-literal = { version = "0.3.1", default-features = false }
libsecp256k1 = { version = "0.3", default-features = false }
parity-bytes = { version = "0.1.2", default-features = false }
rlp = { version = "0.5", default-features = false }
getrandom = { version = "0.2.1", features = ["js"] }

sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }

ethabi = { git = "https://github.com/snowfork/ethabi-decode.git", package = "ethabi-decode", branch = "master", default-features = false }
ethash = { git = "https://github.com/snowfork/ethash.git", branch = "master", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.19"
snowbridge-testutils = { path = "../../primitives/testutils" }
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"

[features]
default = ["std"]
expensive_tests = []
std = [
	"serde",
	"serde-big-array",
	"codec/std",
	"scale-info/std",
	"ethabi/std",
	"ethash/std",
	"ethbloom/std",
	"ethereum-types/std",
	"hex/std",
	"libsecp256k1/std",
	"parity-bytes/std",
	"rlp/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
