[package]
name = "artemis-ethereum"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
ethbloom = { version = "0.11.0", default-features = false }
ethereum-types = { version = "0.11.0", default-features = false, features = ["codec", "rlp", "serialize"] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
hex-literal = { version = "0.3.1", default-features = false }
libsecp256k1 = { version = "0.3", default-features = false }
parity-bytes = { version = "0.1.2", default-features = false }
rlp = { version = "0.5", default-features = false }
serde = { version = "1.0.101", optional = true }
serde-big-array = { version = "0.2", optional = true }
getrandom = { version = "0.2.1", features = ["js"] }

sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1", default-features = false }

ethabi = { git = "https://github.com/snowfork/ethabi-decode.git", branch = "master", package = "ethabi-decode", default-features = false }
ethash = { git = "https://github.com/snowfork/ethash.git", branch = "master", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.19"
artemis-testutils = { path = "../../primitives/testutils" }
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["std"]
expensive_tests = []
std = [
	"serde",
	"serde-big-array",
	"codec/std",
	"ethabi/std",
	"ethash/std",
	"ethbloom/std",
	"ethereum-types/std",
	"hex/std",
	"libsecp256k1/std",
	"parity-bytes/std",
	"rlp/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
