- hosts: rococo

  tasks:
    - debug:
        msg: System {{ nodes }}

    - name: Install packages
      apt:
        pkg:
          - python3-pip
        update_cache: yes

    - name: Install boto3
      pip:
        name: boto3

    - name: Make directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop:
        - /opt/artemis/bin
        - /opt/artemis/data

    - name: Download subkey
      get_url:
        url: https://snowfork-232374692033.s3-eu-west-1.amazonaws.com/subkey
        dest: /usr/local/bin/subkey
        mode: "0755"

    - name: Download relay binary
      get_url:
        url: https://snowfork-232374692033.s3-eu-west-1.amazonaws.com/polkadot
        dest: /opt/artemis/bin/polkadot
        mode: "0755"

    - name: Download Spec
      get_url:
        url: https://snowfork-232374692033.s3-eu-west-1.amazonaws.com/rococo.json
        dest: /opt/artemis/rococo.json
        mode: "0644"
