- hosts: parachain
  serial: 1
  vars:
    relaychain_bootnodes: "/ip4/{{ hostvars['relaychain-node-0'].private_ip_address }}/tcp/30333/p2p/{{ hostvars['relaychain-node-0'].peer_id }}"
    parachain_bootnodes: "/ip4/{{ hostvars['parachain-node-0'].private_ip_address }}/tcp/30333/p2p/{{ hostvars['parachain-node-0'].peer_id }}"

  tasks:
    - name: Create service file
      template:
        src: collator.service.j2
        dest: /etc/systemd/system/collator.service
        owner: root
        group: root
        mode: 0644
      notify: Restart collator

    - name: Make sure service is running
      systemd:
        name: collator
        state: started
        enabled: yes

  handlers:
    - name: Restart collator
      systemd:
        name: collator
        state: restarted
        daemon_reload: yes

- hosts: parachain-node-0
  vars:
    rpc_dns_name: peb-rpc.snowfork.network

  tasks:
    - name: Create nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
