[package]
name = "snowbridge-xcm-support"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.9", default-features = false }

xcm = { git = "https://github.com/paritytech/polkadot.git", branch = "release-v0.9.9", default-features = false }
xcm-executor = { git = "https://github.com/paritytech/polkadot.git", branch = "release-v0.9.9", default-features = false }
xcm-builder = { git = "https://github.com/paritytech/polkadot.git", branch = "release-v0.9.9", default-features = false }

snowbridge-core = { path = "../../primitives/core", default-features = false }

[features]
default = ["std"]
std = [
        "codec/std",
        "sp-std/std",
        "sp-runtime/std",
        "frame-support/std",
        "xcm/std",
        "xcm-executor/std",
        "xcm-builder/std",
        "snowbridge-core/std"
]
