[profile.default]
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 20_000
via_ir = false
test = 'test'
remappings = [
    'canonical-weth=lib/canonical-weth/contracts/',
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
    'openzeppelin=lib/openzeppelin-contracts/contracts/',
    'solmate=lib/solmate/src/',
]
ffi = true


ignored_error_codes = [
    # prevrandao not supported by Anvil VM
    9432
]
