[package]
name = "snowbridge-basic-channel-rpc"
version = "0.1.0"
edition = "2021"
authors = [ "Snowfork <contact@snowfork.com>" ]
repository = "https://github.com/Snowfork/snowbridge"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec = { version = "3.1.5", package = "parity-scale-codec", features = [ "derive" ] }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }

sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-offchain = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
parking_lot = "0.11.0"

snowbridge-basic-channel-merkle-proof = { path = "../merkle-proof" }

[dev-dependencies]
serde_json = "1.0.79"
hex = "0.4.3"
