name: ethereum

on:
  push:
    paths:
      - "core/**"
      - "!core/**/README.md"
    branches:
      - main
  pull_request:
    paths:
      - "core/**"
      - "!core/**/README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.6
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: v18.16.1
          cache: "pnpm"
          cache-dependency-path: core/pnpm-lock.yaml
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install dependencies and Build all
        working-directory: core
        run: pnpm install --frozen-lockfile && pnpm build
      - name: Test
        working-directory: core/packages/contracts
        run: forge test
      - name: Coverage
        working-directory: core/packages/contracts
        run: forge coverage --report=lcov --via-ir
      - name: Lint
        working-directory: core/packages/contracts
        run: pnpm lint
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          working-directory: core/packages/contracts
          files: lcov.info
          flags: solidity
