name: ethereum

on:
  push:
    paths:
      - "core/**"
      - "!core/**/README.md"
    branches:
      - main
  pull_request:
    paths:
      - "core/**"
      - "!core/**/README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: snowbridge-runner
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.14.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: "pnpm"
          cache-dependency-path: core/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: core
        run: pnpm install --frozen-lockfile
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Build
        working-directory: core
        run: pnpm build
      - name: Test
        working-directory: core
        run: pnpm test
      - name: Lint
        working-directory: core
        run: pnpm lint
